In [1]:
import numpy as np

In [2]:
A = np.arange(3,15)
print(A[3])

6


In [7]:
B = np.arange(3,15).reshape((3,4))
print(B[2]) # B[2] 对应的是矩阵B的3rd row
print(B[2][3])
print(B[2][1:3])

[11 12 13 14]
14
[12 13]

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [8]:
for row in B:
    print(row)
print()

for column in B.T:
    print(column)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [9]:
for item in B.flat:
    print(item)

3
4
5
6
7
8
9
10
11
12
13
14


In [47]:
C = np.array([1,1,1])
D = np.array([2,2,2])
print(C.shape)
print(C.T.shape)
print(np.vstack((C,D))) #垂直叠加
print(np.vstack((C,D)).T)

(3,)
(3,)
[[1 1 1]
 [2 2 2]]
[[1 2]
 [1 2]
 [1 2]]


In [71]:
E = np.array([1,1,1])[:,np.newaxis]
print(E)
F = np.array([3,3,3])[:,np.newaxis]
print(np.hstack((E,F)))

[[1]
 [1]
 [1]]
[[1 3]
 [1 3]
 [1 3]]


In [76]:
print(np.concatenate((E,F),axis = 1))
G = np.array([2,2,2,2])[:,np.newaxis]
H = np.array([4,4,4,4])[:,np.newaxis]
print(np.concatenate(([G,H]), axis = 0))

[[1 3]
 [1 3]
 [1 3]]
[[2]
 [2]
 [2]
 [2]
 [4]
 [4]
 [4]
 [4]]


In [77]:
I = np.concatenate(([G,H]), axis = 0)
print(I)

[[2]
 [2]
 [2]
 [2]
 [4]
 [4]
 [4]
 [4]]


In [78]:
print(np.split(I,2,axis = 0)) # axis = 0 竖着分； axis = 1 横着分

[array([[2],
       [2],
       [2],
       [2]]), array([[4],
       [4],
       [4],
       [4]])]


In [80]:
print(np.array_split(I,3,axis = 0)) # split 等分；array_split 不等分
                                    # np.vsplit() np.hsplit()

[array([[2],
       [2],
       [2]]), array([[2],
       [4],
       [4]]), array([[4],
       [4]])]


In [ ]:
# print(np.hsplit(A, 2)) #等于 print(np.split(A, 2, axis=1))