In [101]:
import numpy as np

In [102]:
test_1 = np.array([[1,2,3], [2,3,4]], dtype=np.float)
print(test_array)

[[ 1.  2.  3.]
 [ 2.  3.  4.]]


In [103]:
print(type(test_1))
print('dimension: ', test_1.ndim)
print('shape: ', test_1.shape)
print('size: ', test_1.size)

<class 'numpy.ndarray'>
dimension:  2
shape:  (2, 3)
size:  6


In [104]:
print(test_1.dtype)

float64


In [105]:
test_2 = np.ones((3,4),dtype = np.float)
print(test_2.shape)
print(test_2[0])

(3, 4)
[ 1.  1.  1.  1.]


In [106]:
test_3 = np.arange(10,20).reshape((5,2)) #第一个是row， 第二个是column
print(test_3)

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [107]:
test_4 = np.linspace(10,20,5)
print(test_4)

[ 10.   12.5  15.   17.5  20. ]


In [108]:
test_a = np.arange(0,9)
print(test_a)
test_b = np.arange(10,19)
print(test_b)
print(test_a+test_b)
test_c = test_a*test_b
# test_c.dtype = float
print(test_c<10)
print(np.sin(test_c))

[0 1 2 3 4 5 6 7 8]
[10 11 12 13 14 15 16 17 18]
[10 12 14 16 18 20 22 24 26]
[ True False False False False False False False False]
[ 0.         -0.99999021 -0.90557836  0.96379539 -0.521551   -0.38778164
  0.98358775 -0.3714041  -0.49102159]


In [109]:
dot_1 = np.array([[1,1],[0,1],[1,1]])
print(dot_1)
print()
dot_2 = np.arange(6).reshape((2,3))
print(dot_2)
print()
dot_3 = np.dot(dot_1, dot_2)
# dot_3 = dot_1.dot(dot_2)
dot_4 = np.dot(dot_2, dot_1)
print(dot_3)
print()
print('dot_4: ')
print(dot_4)
print(dot_4[0][0])
print()
print('sum: ',np.sum(dot_4))
print('sum_col',np.sum(dot_4,axis = 0)) #每个column的和
print('sum_row',np.sum(dot_4,axis = 1)) #每个row的和
print('min: ',np.min(dot_4))
print('min_column: ',np.min(dot_4, axis = 0))
print('min_index: ',np.argmin(dot_4))
print('max_index: ',np.argmax(dot_4))
print('mean: ',np.mean(dot_4))
# dot_4.mean()
print('median: ',np.median(dot_4))
print('cumsum: ', np.cumsum(dot_4))
print('diff: ')
print(np.diff(dot_2))
print(np.nonzero(dot_1))
print(np.sort(dot_4))
print(np.transpose(dot_4))
print(np.clip(dot_4,6,7)) # clip(Array,Array_min,Array_max)
                          # num>Array_max, 取 max
                          # num<Array_min, 取 min
                          # 在中间 取原值

[[1 1]
 [0 1]
 [1 1]]

[[0 1 2]
 [3 4 5]]

[[3 5 7]
 [3 4 5]
 [3 5 7]]

dot_4: 
[[ 2  3]
 [ 8 12]]

sum:  25
sum_col [10 15]
sum_row [ 5 20]
min:  2
min_column:  [2 3]
min_index:  0
max_index:  3
mean:  6.25
median:  5.5
cumsum:  [ 2  5 13 25]
diff: 
[[1 1]
 [1 1]]
(array([0, 0, 1, 2, 2]), array([0, 1, 1, 0, 1]))
[[ 2  3]
 [ 8 12]]
[[ 2  8]
 [ 3 12]]
[[6 6]
 [7 7]]
2
